---
---

## Introduction
This is one of the R functions produced to support the development of a package dedicated to the eLTER Research Infrastructure (eLTER RI). In this case it’s about how to generate QR Code of [**eLTER-RI sites or network**](https://deims.org/models) by [**DEIMS-ID**](https://deims.org/docs/deimsid.html) and using [**qrencoder package**](https://github.com/hrbrmstr/qrencoder).


## eLTER_siteFigure
### Prerequisite:
install all required packages
```{r}
library(devtools)
install.packages('jsonlite')
install.packages("sf")
install.packages("rosm")
install_github("rspatial/raster")
install.packages("tmap")
```

## Function eLTER_siteFigure
```{r}
fProduceMapOfSiteFromDEIMS <- function(deimsid) {
  geoBonBiome <- jsonlite::fromJSON(paste0("https://deims.org/", "api/site/", substring(deimsid, 19)))$attributes$environmentalCharacteristics$geoBonBiome
  color <- biomeColor$fill[biomeColor$geoBonBiome == geoBonBiome]
  colorBorder <- biomeColor$border[biomeColor$geoBonBiome == geoBonBiome]
  geoBoundaries <- jsonlite::fromJSON(paste0("https://deims.org/", "api/site/", substring(deimsid, 19)))$attributes$geographic$boundaries
  
  if (is.null(geoBoundaries)) {
    lterCoords <- jsonlite::fromJSON(paste0("https://deims.org/", "api/site/", substring(deimsid, 19)))$attributes$geographic$coordinates
    lterSitesFeaturePointDEIMS <- sf::as_Spatial(sf::st_as_sfc(lterCoords),)
    baseMap <- rosm::osm.raster(lterSitesFeaturePointDEIMS, zoomin = -5)
    # plot(baseMap)
    newBaseMap <- raster::reclassify(baseMap, cbind(NA, 255))
    # plot(newBaseMap)
    mapOfSite <-
      tmap::tm_shape(newBaseMap, ) + tmap::tm_rgb() +
      tmap::tm_shape(lterSitesFeaturePointDEIMS) +
      tmap::tm_dots(size = 1, shape = 16, palette = color, title = NA, legend.show = TRUE) +
      # tmap::tm_text(text = "long_name", col = "black", fontfamily = "sans", size = 1.5) +
      tmap::tm_compass(type = "8star", position = c("right", "bottom")) +
      tmap::tm_scale_bar(position = c("right", "bottom")) +
      tmap::tm_layout(main.title = paste0(jsonlite::fromJSON(paste0("https://deims.org/", "api/site/", substring(deimsid, 19)))$title),
                      main.title.position = "center",
                      main.title.color = "black",
                      main.title.fontfamily = "sans",
                      main.title.size = 1,
                      legend.bg.color = "white",
                      legend.position = c(0.75, 0.9),
                      legend.width = -0.24
      ) +
      # tmap::tm_credits(paste0("DEIMS ID: ", centroidsFeatureSPItalySelected$DEIMS_ID),
      #                  size = 0.7,
      #                  fontfamily = "sans",
      #                  position = c("left", "top")) +
      tmap::tm_credits("© OpenStreetMap contributors - \nhttps://www.openstreetmap.org/",
                       size = 0.6,
                       fontfamily = "sans",
                       position = c("left", "bottom")) +
      tmap::tm_basemap(leaflet::providers$Stamen.Watercolor)
  } else {
    lterSitesFeatureDEIMS <- sf::as_Spatial(sf::st_as_sfc(geoBoundaries),)
    baseMap <- rosm::osm.raster(lterSitesFeatureDEIMS)
    # plot(baseMap)
    newBaseMap <- raster::reclassify(baseMap, cbind(NA, 255))
    # plot(newBaseMap)
    mapOfSite <-
      tmap::tm_shape(newBaseMap, ) + tmap::tm_rgb() +
      tmap::tm_shape(lterSitesFeatureDEIMS) +
      tmap::tm_borders(col = colorBorder) +
      tmap::tm_fill(col = color) +
      # tmap::tm_text(text = "long_name", col = "black", fontfamily = "sans", size = 1.5) +
      tmap::tm_compass(type = "8star", position = c("right", "bottom")) +
      tmap::tm_scale_bar(position = c("right", "bottom")) +
      tmap::tm_layout(main.title = paste0(jsonlite::fromJSON(paste0("https://deims.org/", "api/site/", substring(deimsid, 19)))$title),
                      main.title.position = "center",
                      main.title.color = "black",
                      main.title.fontfamily = "sans",
                      main.title.size = 1,
                      legend.bg.color = "white",
                      legend.position = c(0.75, 0.9),
                      legend.width = -0.24
      ) +
      # tmap::tm_credits(paste0("DEIMS ID: ", centroidsFeatureSPItalySelected$DEIMS_ID),
      #                  size = 0.7,
      #                  fontfamily = "sans",
      #                  position = c("left", "top")) +
      tmap::tm_credits("© OpenStreetMap contributors - \nhttps://www.openstreetmap.org/",
                       size = 0.6,
                       fontfamily = "sans",
                       position = c("left", "bottom")) +
      tmap::tm_basemap(leaflet::providers$Stamen.Watercolor)
  }
  
  # mapOfSite
  tmap::tmap_save(
    tm = mapOfSite,
    filename = paste0("images/", substring(deimsid, 19), ".png"),
    dpi = 400
  )
}

fProduceMapOfSiteFromDEIMS('https://deims.org/f30007c4-8a6e-4f11-ab87-569db54638fe')
```
